Add pylint checker rule
theY4Kman/pytest-only pull request #10
Opened 2022-05-24 10:22 UTC by nikolaik

We found it useful to lint usage of this pytest marker and maybe others do too.

2022-05-25 04:48 UTC, theY4Kman requested changes
ooo, this is fantastic, and a wonderful idea! I use a Live Template in PyCharm to expand `only` to:
```py
#XXX######################################################################################
@getattr(__import__('pytest').mark, 'only')
#XXX######################################################################################
```
... because it's really, really hard to miss when doing a `git diff` :P I really like the idea of bundling a lint rule.

I've only got some minor nits. I might also want to move `pytest_only.checker` to `pytest_only.ext.pylint` or something, just for organization's sake. And I might add an optional/extras package set to the `pyproject.toml` just to make the dependencies more concrete.

This is baller, though. Thank you so much for submitting it! <3

2022-05-25 04:48 UTC, theY4Kman commented on README.rst
> +If you use pylint you can help avoid commiting stray mark.onlys. Enable the pylint checker in your plugins and enabled the `unexpected-focused` rule.
nit: spelling, wording
```suggestion
If you use pylint, you can help avoid committing stray `only` marks with the bundled plugin. Just enable the pylint checker in your plugins and enable the `unexpected-focused` rule.
```

2022-05-25 04:48 UTC, theY4Kman commented on pytest_only/checker.py
> +    linter.register_checker(MarkOnlyCheckerChecker(linter))
nit: newline at EOF
```suggestion
    linter.register_checker(MarkOnlyCheckerChecker(linter))

```

2022-05-25 10:36 UTC, nikolaik commented
Nice, will update with your suggestions. i'll try to add a test too

2022-05-25 10:37 UTC, nikolaik commented
Neat trick with the live template in pycharm, never tried those 💡

2022-05-29 22:09 UTC, theY4Kman commented
I pushed a bunch of stuff to your branch. It always feels a little weird pushing to someone else's repo :P But it sure is convenient, and it doesn't ditch the commit author field (like pulling it into my own branch and merging straight to master/opening a separate PR might).

Anywhoozlewoozle, I did the restructuring to `pytest_only.ext.pylint`, added a bunch of tests (using [pytest-pylint](https://github.com/carsongee/pytest-pylint)), and also realized `@pytest.mark.only` on a function isn't the only way to apply marks, so I added support for class-level decorators and `pytestmark = ...` at class/module levels. I also added support for async function defs, just in case anyone uses it with pytest-asyncio et al (like moi).

I'd really like to know if the changes I made still work in your env before I merge, though.

2022-05-29 22:39 UTC, nikolaik commented
Most excellent! Will test your changes tomorrow!

2022-05-30 14:32 UTC, nikolaik commented
Very nice, works just as expected, bravo!  Minus the comment on python version dependency resolution

2022-06-14 05:29 UTC, theY4Kman commented
Agh, sorry, I got married this weekend, and things have been hectic. That's my excuse :P I'll revisit this later tonight, and get it all released.

2022-06-14 07:08 UTC, theY4Kman commented on pyproject.toml
> +    {version = '>=7.1', python = '^3.7'},
Oops! Yes!

2022-06-14 07:17 UTC, theY4Kman commented
Thanks for that version constraint fix. I wish I knew how to include that installation path in the tests; right now, it's using poetry to install all deps, then uses pip to override whatever version of pytest it installed =/

Also, thank you so much for taking the time to open the pull request, and for thinking about other peeps who'll find this very handy :) Aaaand sorry for the delay in merging :P

2022-06-14 07:17 UTC, merged

2022-06-14 09:46 UTC, nikolaik commented
Wowza, congrats @theY4Kman and cheers to you both 🥂